
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Dec 13 11:43:27 CET 2019
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FSI = 31;
  public static final int TYPEAPP = 41;
  public static final int SI = 28;
  public static final int ASSOCIER = 39;
  public static final int INTERFACE = 45;
  public static final int TYPEAUTREAPP = 44;
  public static final int BALISEDECLSCENARIO = 10;
  public static final int DOUBLEEG = 23;
  public static final int BALISEFINDECLCOMMANDE = 13;
  public static final int AUTREAPPAREIL = 36;
  public static final int VIRG = 14;
  public static final int PAROUV = 21;
  public static final int BALISEDEBDECLSCENARII = 8;
  public static final int PLUGR = 27;
  public static final int BALISEFINDECLINTERF = 7;
  public static final int PVIRG = 17;
  public static final int PARFERM = 22;
  public static final int BALISEDEBDECLAPP = 4;
  public static final int EOF = 0;
  public static final int ETAT = 42;
  public static final int FAIT = 26;
  public static final int BALISEFINDECLAPP = 5;
  public static final int error = 1;
  public static final int FAIRE = 25;
  public static final int POURTOUT = 24;
  public static final int IDENT = 47;
  public static final int ACTION = 43;
  public static final int EXECUTERSCENARIO = 38;
  public static final int SINON = 30;
  public static final int ALORS = 29;
  public static final int BALISEDEBDECLINTERF = 6;
  public static final int ACCCFERM = 20;
  public static final int BALISEFINPROG = 3;
  public static final int MESSAGE = 33;
  public static final int EG = 19;
  public static final int POINT = 15;
  public static final int PROGRAMMER = 37;
  public static final int BALISEDEBDECLCOMMANDE = 12;
  public static final int UNDERSCORE = 32;
  public static final int DEFINIR = 34;
  public static final int ENTIER = 40;
  public static final int CHAINE = 46;
  public static final int ACCOUV = 18;
  public static final int MCETAT = 35;
  public static final int BALISEDEBPROG = 2;
  public static final int DP = 16;
  public static final int BALISEFINDECLSCENARII = 9;
  public static final int BALISEFINSCENARIO = 11;
}

